apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: harbor.hayward.cf-app.com/library/petclinic:b4.20200220.234125
        name: petclinic
        ports:
        - containerPort: 8080
